### PR TITLE
Removed unused dependecies and Imports

### PR DESCRIPTION
**Pull request by Abdulkeza**
# What does this PR do?
- [x] It removes all statements which are not required

# Description of Task to be completed?
- [x] Removed unused dependencies
- [x] Removed unused imports

# How should this be manually tested?
[Clone](https://github.com/atlp-rwanda/phantom-fe-codebandits.git)
-clone
-npm i
-npm run start

# Any background context you want to provide?
(N/A)
# What are the relevant pivotal tracker stories?
[TDMONwwl](https://trello.com/c/TDMONwwl/7-clean-up-unused-dependencies)

# Questions:
N/A

### CODE REVIEW

**Review by feyton — APPROVED** [review]
The file tree is clean and everything is working as well.

**Review by Yvad60 — COMMENTED** [review]
is `npm run start` working for you? I cloned and did `npm install` and everything but the server is not working I'm getting this error `ERROR in main Module not found: Error: Can't resolve 'babel-loader'`

**Review by feyton — CHANGES_REQUESTED** [review]
Some modules were removed while they are still needed
Ex: Babel loader

Check again the modules that are not related to the tests and add them back.
Currently I have 2 errors

**Review by samyshyaka — COMMENTED** [review]
Nice work abdul,
There is a file named 'setupTests.js', it is not in the changed files for this PR but try to go back to it and work on the spacing between the lines. Otherwise you did a great job.

**Comment by Abdulkeza** [comment]
Now everything is working perfectly

**Review by feyton — APPROVED** [review]
@Abdulkeza 
Everything is working on my end and the refactoring is great.
It passes all check and is being rendered in the browser.

**Pull request merged**
